version: '2'

services:
  openstack:
    build: .
    volumes:
     - /Users/c13141/projects/Rackspace/devstack:/github/devstack
    ports:
      - "8000:80"
      - "4443:443"
    privileged: true
    links:
     - rabbitmq_openstack
     - mysql_openstack

  rabbitmq_openstack:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_PASS=st4ckb0ss
      - RABBITMQ_DEFAULT_USER=stackrabbit
  mysql_openstack:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=st4ckb0ss
